name: tech-article-recommender-infra
description: aws for tech-article-recommender
runtime:
  name: nodejs
  options:
    packagemanager: yarn
config:
  pulumi:tags:
    value:
      pulumi:template: aws-typescript
